#!/usr/bin/python
#a: James Burke
#e: jburke@quotemedia.com
#v: 0.3
from urllib2 import urlopen
from lock import Lock
from lookup import Lookup
import datetime
import json


timeout=10 		#Timeout for request to nginx status page
url="http://10.2.2.1/status"
nagios=None		#Nagios instance url

lock=Lock()
name=Lookup("names.json")

print lock.lock
if lock.create():
	statusJson=json.loads(urlopen(url,timeout=timeout).read())
	for upstream in statusJson["upstreams"]:
		print upstream
		for instance in statusJson["upstreams"][upstream]:
			state=instance["state"]
			downtime=str(datetime.timedelta( seconds = (instance["downtime"]/1000)))
			host=name.lookup(instance["server"], True)
			print host + " - " + state + " - " + downtime
	lock.destroy()
	print name.names
	name.writeDNS()
